// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiWo7VphXKrQ0ZpVl6r9KsE3jGuhQq2lE',
    appId: '1:49562030048:web:50e8f3e7f56e51636da585',
    messagingSenderId: '49562030048',
    projectId: 'aiot-proj',
    authDomain: 'aiot-proj.firebaseapp.com',
    storageBucket: 'aiot-proj.appspot.com',
    measurementId: 'G-TEYQCHNKKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQX_X5zFPwS8dzLMeRqLx7-q7DvmMfg7Y',
    appId: '1:49562030048:android:d2d72d3df5b3bf396da585',
    messagingSenderId: '49562030048',
    projectId: 'aiot-proj',
    storageBucket: 'aiot-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWZ2uhPJH7bV03imHKn6xm5zGk11gsKjU',
    appId: '1:49562030048:ios:e995782afc517bb56da585',
    messagingSenderId: '49562030048',
    projectId: 'aiot-proj',
    storageBucket: 'aiot-proj.appspot.com',
    iosBundleId: 'com.example.aiotProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWZ2uhPJH7bV03imHKn6xm5zGk11gsKjU',
    appId: '1:49562030048:ios:e995782afc517bb56da585',
    messagingSenderId: '49562030048',
    projectId: 'aiot-proj',
    storageBucket: 'aiot-proj.appspot.com',
    iosBundleId: 'com.example.aiotProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiWo7VphXKrQ0ZpVl6r9KsE3jGuhQq2lE',
    appId: '1:49562030048:web:9af610f89b84cf9e6da585',
    messagingSenderId: '49562030048',
    projectId: 'aiot-proj',
    authDomain: 'aiot-proj.firebaseapp.com',
    storageBucket: 'aiot-proj.appspot.com',
    measurementId: 'G-CJLC3DG1SR',
  );
}
